name: ${artifactId}
version: ${version}
author: KUDONG
description: ${description}
main: kr.kudong.framework.bungee.FrameworkCore
api-version: ${bukkit-api.version}
commands:
    ws:
        aliases: [귓,귓속말,rnlt]
        description: communication test
        usage: /aldarcommsend <target> [data]