name: Kudong-entity-riding
version: ${version}
author: KUDONG
description: ${description}
api-version: ${bukkit-api.version}
main: kr.kudong.entity.RidingCore
commands:
    ride:
      aliases: [탈것,xkfrjt]