name: Kudong-framework
version: ${version}
author: KUDONG
description: ${description}
api-version: ${bukkit-api.version}
main: kr.kudong.framework.FrameworkCore
depend: [PlaceholderAPI]
commands:
    scb:
      aliases: [스코어보드,스보] 
    kudong:
      aliases: [쿠동]
    bc:
      aliases: [방송]  