name: Kudong-framework
version: ${version}
author: KUDONG
description: ${description}
api-version: ${bukkit-api.version}
main: kr.kudong.framework.FrameworkCore
depend: [PlaceholderAPI]
softdepend: [HQTowny,ChestCommands]
commands:
    scb:
      aliases: [스코어보드,스보]
    member:
      aliases: [멤버,멤,apa] 
    kudong:
      aliases: [쿠동,kd]
    bc:
      aliases: [공지]  
    ws:
      aliases: [귓,귓속말,rnlt]